version: '3.7'
services:
  iwb-mongodb:
    container_name: iwb-mongodb
    image: 'bitnami/mongodb:latest'
    restart: unless-stopped
    environment:
      - MONGODB_ROOT_PASSWORD=iwb
    networks:
      - iwb-network
    ports:
      - 27017:27017
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
networks:
  iwb-network:
    driver: bridge
volumes:
  mongodb_data:
    driver: local
