version: '3.7'
services:
  iwb-redis:
    container_name: iwb-redis
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - iwb-network
    ports:
      - 6379:6379
    volumes:
      - 'redis_data:/bitnami/redis/data'
networks:
  iwb-network:
    driver: bridge
volumes:
  redis_data:
    driver: local
